// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppUpdateEvent = { "event": "downloadStarted", "data": { total: number | null, } } | { "event": "downloadProgress", "data": { downloaded: number, total: number | null, } } | { "event": "installing" };
