// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The OS/2 embedding permission, which is the only licence statement a font makes in a form a
 * program can act on. `FontNest` reports it and never decides anything from it: installing a font
 * on the computer it came to is not embedding.
 */
export type EmbeddingPermission = "installable" | "restricted" | "previewAndPrint" | "editable" | "unknown";
