// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFaceSummary } from "./FontFaceSummary";

export type FontFamilySummary = { id: string, name: string, faceCount: number, fileCount: number, styles: Array<string>, weights: Array<number>, formats: Array<string>, sources: Array<string>, monospaced: boolean, hasConflict: boolean, faces: Array<FontFaceSummary>, };
