// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontParserJsonSection } from "./FontParserJsonSection";

/**
 * Ordered messages for one parser-snapshot export.
 *
 * The document arrives in chunks instead of as a single string: a large snapshot never
 * becomes one oversized IPC payload, and the interface can show progress and give up part
 * way through.
 */
export type FontParserJsonEvent = { "event": "started", "data": { faceId: string, parserName: string, parserVersion: string, totalBytes: number, chunkCount: number, truncated: boolean, unicodeMappings: FontParserJsonSection, glyphs: FontParserJsonSection, } } | { "event": "chunk", "data": { index: number, text: string, } } | { "event": "finished" } | { "event": "cancelled" };
