// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontGlyphBounds } from "./FontGlyphBounds";
import type { FontGlyphOutlineHandle } from "./FontGlyphOutlineHandle";
import type { FontGlyphOutlinePoint } from "./FontGlyphOutlinePoint";

export type FontGlyphOutline = { faceId: string, codepoint: number, glyphId: number, glyphName: string | null, unitsPerEm: number, advanceWidth: number | null, leftSideBearing: number | null, bounds: FontGlyphBounds | null, pathData: string, points: Array<FontGlyphOutlinePoint>, handles: Array<FontGlyphOutlineHandle>, contourCount: number, outlineAvailable: boolean, };
