// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontGlyphVariationValue } from "./FontGlyphVariationValue";

export type FontGlyphOutlineRequest = { faceId: string, codepoint: number, variations: Array<FontGlyphVariationValue>, };
