// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FontVariationAxis = { tag: string, nameId: number, minimum: number, default: number, maximum: number, hidden: boolean, };
