// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontOrigin } from "./FontOrigin";

export type FontFaceSummary = { id: string, postScriptName: string, styleName: string, style: string, weight: number, format: string, origin: FontOrigin, fileName: string, faceIndex: number, monospaced: boolean, 
/**
 * Carries variation axes, so one file covers a range of weights or widths.
 */
variable: boolean, };
