// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a font came from, ordered from the fonts the operating system owns to the ones
 * somebody added. Ordering matters: it decides how a family lists mixed origins.
 */
export type FontOrigin = "systemDefault" | "machineInstalled" | "userInstalled" | "unknown";
