// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFaceMetrics } from "./FontFaceMetrics";
import type { FontFaceNames } from "./FontFaceNames";
import type { FontFaceProperties } from "./FontFaceProperties";
import type { FontVariationAxis } from "./FontVariationAxis";

export type FontFaceInspection = { faceId: string, parserName: string, parserVersion: string, metrics: FontFaceMetrics, names: FontFaceNames, properties: FontFaceProperties, variationAxes: Array<FontVariationAxis>, unicodeCodepoints: Array<number>, };
