// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of one parser-snapshot section made it into the document.
 *
 * The snapshot is a bounded diagnostic sample, so every capped section reports what it
 * carries against what the face actually holds; the interface says so rather than letting
 * a partial list read as the whole font.
 */
export type FontParserJsonSection = { included: number, total: number, };
