// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FontFaceSummary = { id: string, postScriptName: string, styleName: string, style: string, weight: number, format: string, source: string, fileName: string, faceIndex: number, monospaced: boolean, };
