// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefusedFontRemoval } from "./RefusedFontRemoval";

/**
 * What removing one managed font did.
 */
export type FontRemovalReport = { 
/**
 * True when the font was taken out of service and set aside.
 */
removed: boolean, 
/**
 * Set when `FontNest` would not remove it, with the check that stopped. The font is still
 * installed and still registered.
 */
refused: RefusedFontRemoval | null, };
