// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FontFaceNames = { fullName: string | null, version: string | null, manufacturer: string | null, designer: string | null, description: string | null, license: string | null, };
