// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingPermission } from "./EmbeddingPermission";

/**
 * What a font says about who may use it and how. Read from the font, never from a file name.
 */
export type FontLicenceSummary = { 
/**
 * What the font's own licence field says, trimmed and capped for display.
 */
description: string | null, url: string | null, 
/**
 * What the embedding permissions in the font allow, in the font's own terms.
 */
embedding: EmbeddingPermission, };
