// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why `FontNest` would not remove a font it has a record of installing.
 *
 * Each value names the check that stopped, because a font somebody replaced and a ledger somebody
 * edited need different things said about them.
 */
export type FontRemovalRefusal = "unknownSource" | "locationUnavailable" | "recordMismatch" | "missing" | "redirected" | "outsideFontFolder" | "changed" | "notRegistered" | "protected" | "unreadable";
