// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontEmbeddingProperties } from "./FontEmbeddingProperties";

export type FontFaceProperties = { glyphCount: number, unicodeCodepointCount: number, tableCount: number, weight: number, width: number, italicAngle: number, traits: Array<string>, embedding: FontEmbeddingProperties, };
