// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFaceSummary } from "./FontFaceSummary";
import type { FontOrigin } from "./FontOrigin";

export type FontFamilySummary = { id: string, name: string, faceCount: number, fileCount: number, styles: Array<string>, weights: Array<number>, formats: Array<string>, origins: Array<FontOrigin>, monospaced: boolean, 
/**
 * True when any face in the family carries variation axes.
 */
variable: boolean, hasConflict: boolean, faces: Array<FontFaceSummary>, };
