// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FontParserJsonRequest = { faceId: string, 
/**
 * Caller-generated ID for this export, so it can be cancelled while it still runs.
 */
exportId: string, };
