// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FontFaceMetrics = { unitsPerEm: number, ascender: number, capitalHeight: number | null, capitalHeightSource: string, xHeight: number | null, xHeightSource: string, baseline: number, descender: number, lineGap: number, };
