// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleFontInstallResult = { familyId: string, familyName: string, installedArtifactIds: Array<string>, alreadyInstalledArtifactIds: Array<string>, };
