// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefusedFontRemoval } from "./RefusedFontRemoval";

export type GoogleFontUninstallResult = { familyId: string, familyName: string, removedArtifactIds: Array<string>, 
/**
 * Fonts `FontNest` would not remove. They are still installed and still registered.
 */
refused: Array<RefusedFontRemoval>, };
