// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleFontArtifactSummary = { id: string, fileName: string, style: string, format: string, sizeBytes: number, installed: boolean, };
