// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleFontFamilySummary } from "./GoogleFontFamilySummary";

export type GoogleFontPage = { families: Array<GoogleFontFamilySummary>, total: number, offset: number, limit: number, snapshot: string, };
