// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleFontArtifactSummary } from "./GoogleFontArtifactSummary";

export type GoogleFontFamilyDetails = { id: string, family: string, category: string, subsets: Array<string>, license: string, lastModified: string, version: string, previewArtifactId: string, artifacts: Array<GoogleFontArtifactSummary>, };
