// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleFontPreview = { artifactId: string, fontFamily: string, 
/**
 * `fontnest-preview` URL for the verified bytes. Never a data URL and never a path:
 * the web view fetches through the internal protocol by opaque handle.
 */
previewUrl: string, };
