// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleFontFamilySummary = { id: string, family: string, category: string, subsets: Array<string>, license: string, artifactCount: number, previewArtifactId: string, installed: boolean, };
