// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One face inside a chosen file, as the parser read it.
 */
export type ImportFaceSummary = { familyName: string, subfamilyName: string, fullName: string, postScriptName: string, version: string | null, weight: number, italic: boolean, glyphCount: number, };
