// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontLicenceSummary } from "./FontLicenceSummary";
import type { ImportFaceSummary } from "./ImportFaceSummary";
import type { ImportVerdict } from "./ImportVerdict";

/**
 * One chosen file and everything the review found in it.
 */
export type ImportCandidate = { 
/**
 * The path the person chose, for them to recognize the file by. It is display only: an
 * import re-reads and re-decides everything from the file itself.
 */
sourcePath: string, fileName: string, 
/**
 * For display. Saturated rather than widened: this crosses to an interface that shows it as
 * "about 2 MB", and a number that large is already a refusal for being too large.
 */
sizeBytes: number, verdict: ImportVerdict, 
/**
 * The name the file would be installed under, when it would be installed at all.
 */
installedFileName: string | null, faces: Array<ImportFaceSummary>, licence: FontLicenceSummary | null, };
