// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportVerdict } from "./ImportVerdict";

/**
 * What one file's import actually did.
 */
export type ImportOutcome = { sourcePath: string, fileName: string, installed: boolean, 
/**
 * The family and style now installed, when it was.
 */
displayName: string | null, 
/**
 * Why it was not installed, in the same words the review would have used.
 */
refusal: ImportVerdict | null, 
/**
 * Set when the import failed for a reason the review could not have seen, such as the
 * file changing underneath it or the operating system refusing the registration.
 */
failure: string | null, };
