// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `FontNest` would do with one chosen file.
 */
export type ImportVerdict = "installable" | "alreadyInstalled" | "repeatedSelection" | "previewOnly" | "unreadable" | "tooLarge" | "systemOwned" | "missing";
