// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportCandidate } from "./ImportCandidate";

/**
 * Everything one review found, in the order the files were chosen.
 */
export type ImportPlan = { candidates: Array<ImportCandidate>, 
/**
 * Total bytes of the files that would be installed, for display.
 */
installableBytes: number, 
/**
 * True when the selection was cut off at the limit rather than read whole.
 */
truncated: boolean, };
