// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preferences } from "./Preferences";
import type { PreferencesRecovery } from "./PreferencesRecovery";

/**
 * What a load produced: the settings to use, and whether anything had to be recovered from.
 */
export type LoadedPreferences = { preferences: Preferences, 
/**
 * `None` on an ordinary load, including the first launch, when there is simply no document.
 */
recovery: PreferencesRecovery | null, };
