// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why `FontNest` cannot mutate managed font state right now.
 */
export type ManagedStorageRecovery = "ledgerUnavailable" | "schemaTooNew" | "locked";
