// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedFontSummary } from "./ManagedFontSummary";
import type { QuarantinedFontSummary } from "./QuarantinedFontSummary";

/**
 * Everything `FontNest` is looking after: what is installed, and what it has set aside.
 */
export type ManagedFontInventory = { installed: Array<ManagedFontSummary>, quarantined: Array<QuarantinedFontSummary>, };
