// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedStorageRecovery } from "./ManagedStorageRecovery";

/**
 * Whether installing, updating, uninstalling, repairing, and restoring fonts are available in
 * this session. Browsing, previewing, and inspecting stay available either way.
 */
export type ManagedStorageStatus = { writable: boolean, reason: ManagedStorageRecovery | null, };
