// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One font `FontNest` has installed on this computer, whatever put it there.
 */
export type ManagedFontSummary = { 
/**
 * The identifier a removal names it by.
 */
id: string, 
/**
 * Which source put it here: a provider, or this computer.
 */
provider: string, familyName: string, displayName: string, 
/**
 * True when the font came from a file somebody imported rather than from a provider.
 */
imported: boolean, };
