// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DensityPreference } from "./DensityPreference";
import type { ThemePreference } from "./ThemePreference";

/**
 * The settings themselves. Every field carries a default, so a document written by an older
 * build, or one somebody trimmed by hand, still loads: the missing parts simply are not set.
 */
export type Preferences = { theme: ThemePreference, density: DensityPreference, focusOutlines: boolean, previewText: string, sidebarCollapsed: boolean, pinnedFamilyIds: Array<string>, 
/**
 * Where the interface was: the view, the selection, the filters, the scroll position. Stored
 * as it arrives and handed back the same way; see the note at the top of this file.
 */
session: Record<string, unknown> | null, };
