// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the settings on disk could not be used, when that happens.
 */
export type PreferencesRecovery = "unreadable" | "newerVersion";
