// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One font a removal set aside, and has not been asked to put back.
 */
export type QuarantinedFontSummary = { id: string, provider: string, familyName: string, displayName: string, imported: boolean, 
/**
 * Seconds since the Unix epoch, so the interface can say how long ago.
 *
 * Typed as a number rather than left to the default: this crosses as JSON, where it is a
 * number, and a binding that said `bigint` would describe something that never arrives.
 */
removedAt: number, 
/**
 * What the set-aside file is holding, so the space can be named before it is reclaimed.
 * Zero when the file is no longer there to measure.
 */
sizeBytes: number, };
