// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontRemovalRefusal } from "./FontRemovalRefusal";

/**
 * One font a removal left alone, and why.
 */
export type RefusedFontRemoval = { artifactId: string, displayName: string, reason: FontRemovalRefusal, };
