// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UninstallGoogleFontRequest = { familyId: string, 
/**
 * The artifacts to remove. An empty list means every artifact of the family that `FontNest`
 * installed.
 */
artifactIds: Array<string>, };
