// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalFontFaceSummary } from "./LocalFontFaceSummary";

export type ValidatedLocalFont = { 
/**
 * Opaque handle the internal preview protocol resolves to validated bytes.
 */
handle: string, 
/**
 * Synthetic family name so a duplicate installed family cannot shadow the preview.
 */
previewFamily: string, 
/**
 * Internal-protocol URL the web view loads the validated bytes from.
 */
previewUrl: string, 
/**
 * Sanitized display file name. Never an authoritative filesystem path.
 */
fileName: string, format: string, faceCount: number, faces: Array<LocalFontFaceSummary>, };
